print("안녕")
print(30,"살 입니다")
print('안녕','hi','hello')
print("안녕하세요"+"반갑습니다")
print("안녕안녕안녕")
print("30"+"살입니다")
print(str(30)+"살입니다")
print(30,"살 입니다")
print(30,"살 입 니다")

print('hello world1')
print("안녕"*10)
print('안녕','hi','hello')
print(str(30)+"살입니다")
print("30"+"살입니다")      

